### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by nicoga97** [knative-extensions/eventing-autoscaler-keda#365]
Hello, is this project alive? I'm trying to find the project in which is being addressed the integration of KEDA with Knative serving (not streaming) is this the right one? I would like to contribute 😃

**Comment by tomkerkhove** [comment]
Adding @zroubalik

**Comment by pierDipi** [comment]
Hi @nicoga97, can you please describe the use case for using KEDA with _serving_?

**Comment by WoWsj** [comment]
@pierDipi Hello, I'm also interested with using KEDA with serving.

Especially, I am interested with cron scalers (https://keda.sh/docs/2.11/scalers/cron/) in KEDA.

Because, 

- When user actually know when the traffic will burst

or

- execute some batch jobs using serving, so scale up from zero before batch start(don't want to wait uptime)
